python turn_extractor.py snapshots_9_100.dat
python turn_extractor.py snapshots_7_35.dat
python turn_extractor.py snapshots_9_217.dat
python turn_extractor.py snapshots_2_145.dat
python turn_extractor.py snapshots_5_16.dat
python turn_extractor.py snapshots_9_71.dat
python turn_extractor.py snapshots_3_73.dat
python turn_extractor.py snapshots_6_139.dat
python turn_extractor.py snapshots_4_78.dat
python turn_extractor.py snapshots_3_239.dat
python turn_extractor.py snapshots_0_42.dat
python turn_extractor.py snapshots_0_93.dat
python turn_extractor.py snapshots_2_139.dat
python turn_extractor.py snapshots_2_61.dat
python turn_extractor.py snapshots_6_252.dat
python turn_extractor.py snapshots_0_110.dat
python turn_extractor.py snapshots_3_152.dat
python turn_extractor.py snapshots_2_5.dat
python turn_extractor.py snapshots_6_27.dat
python turn_extractor.py snapshots_6_194.dat
python turn_extractor.py snapshots_8_200.dat
python turn_extractor.py snapshots_5_107.dat
python turn_extractor.py snapshots_8_63.dat
python turn_extractor.py snapshots_3_245.dat
python turn_extractor.py snapshots_6_145.dat
python turn_extractor.py snapshots_0_207.dat
python turn_extractor.py snapshots_9_1.dat
python turn_extractor.py snapshots_3_183.dat
python turn_extractor.py snapshots_8_117.dat
python turn_extractor.py snapshots_6_283.dat
python turn_extractor.py snapshots_0_45.dat
python turn_extractor.py snapshots_0_94.dat
python turn_extractor.py snapshots_2_66.dat
python turn_extractor.py snapshots_0_117.dat
python turn_extractor.py snapshots_6_255.dat
python turn_extractor.py snapshots_3_155.dat
python turn_extractor.py snapshots_2_2.dat
python turn_extractor.py snapshots_5_217.dat
python turn_extractor.py snapshots_6_20.dat
python turn_extractor.py snapshots_6_193.dat
python turn_extractor.py snapshots_8_207.dat
python turn_extractor.py snapshots_8_64.dat
python turn_extractor.py snapshots_5_100.dat
python turn_extractor.py snapshots_0_200.dat
python turn_extractor.py snapshots_6_142.dat
python turn_extractor.py snapshots_8_110.dat
python turn_extractor.py snapshots_3_184.dat
python turn_extractor.py snapshots_9_6.dat
python turn_extractor.py snapshots_6_284.dat
python turn_extractor.py snapshots_0_39.dat
python turn_extractor.py snapshots_7_32.dat
python turn_extractor.py snapshots_9_107.dat
python turn_extractor.py snapshots_7_155.dat
python turn_extractor.py snapshots_9_210.dat
python turn_extractor.py snapshots_2_142.dat
python turn_extractor.py snapshots_5_11.dat
python turn_extractor.py snapshots_9_76.dat
python turn_extractor.py snapshots_3_129.dat
python turn_extractor.py snapshots_6_229.dat
python turn_extractor.py snapshots_3_74.dat
python turn_extractor.py snapshots_8_18.dat
python turn_extractor.py snapshots_5_8.dat
python turn_extractor.py snapshots_9_175.dat
python turn_extractor.py snapshots_7_40.dat
python turn_extractor.py snapshots_9_262.dat
python turn_extractor.py snapshots_2_68.dat
python turn_extractor.py snapshots_2_130.dat
python turn_extractor.py snapshots_5_63.dat
python turn_extractor.py snapshots_5_219.dat
python turn_extractor.py snapshots_0_119.dat
python turn_extractor.py .snapshots_0_1.dat.swp
python turn_extractor.py snapshots_8_209.dat
python turn_extractor.py snapshots_9_8.dat
python turn_extractor.py snapshots_9_109.dat
python turn_extractor.py snapshots_0_37.dat
python turn_extractor.py snapshots_4_119.dat
python turn_extractor.py snapshots_9_78.dat
python turn_extractor.py snapshots_2_14.dat
python turn_extractor.py snapshots_6_227.dat
python turn_extractor.py snapshots_0_165.dat
python turn_extractor.py snapshots_3_127.dat
python turn_extractor.py snapshots_6_52.dat
python turn_extractor.py snapshots_1_59.dat
python turn_extractor.py snapshots_8_275.dat
python turn_extractor.py snapshots_8_16.dat
python turn_extractor.py snapshots_4_71.dat
python turn_extractor.py snapshots_3_230.dat
python turn_extractor.py snapshots_6_83.dat
python turn_extractor.py snapshots_6_130.dat
python turn_extractor.py snapshots_0_272.dat
python turn_extractor.py snapshots_5_6.dat
python turn_extractor.py snapshots_8_162.dat
python turn_extractor.py snapshots_0_30.dat
python turn_extractor.py snapshots_9_219.dat
python turn_extractor.py snapshots_5_18.dat
python turn_extractor.py snapshots_2_13.dat
python turn_extractor.py snapshots_0_162.dat
python turn_extractor.py snapshots_6_220.dat
python turn_extractor.py snapshots_3_120.dat
python turn_extractor.py snapshots_6_55.dat
python turn_extractor.py snapshots_8_272.dat
python turn_extractor.py snapshots_3_237.dat
python turn_extractor.py snapshots_8_11.dat
python turn_extractor.py snapshots_4_76.dat
python turn_extractor.py snapshots_0_275.dat
python turn_extractor.py snapshots_6_84.dat
python turn_extractor.py snapshots_6_137.dat
python turn_extractor.py snapshots_8_165.dat
python turn_extractor.py snapshots_5_1.dat
python turn_extractor.py snapshots_7_47.dat
python turn_extractor.py snapshots_9_172.dat
python turn_extractor.py snapshots_9_265.dat
python turn_extractor.py snapshots_2_137.dat
python turn_extractor.py snapshots_5_64.dat
python turn_extractor.py snapshots_6_29.dat
python turn_extractor.py snapshots_0_209.dat
python turn_extractor.py snapshots_5_109.dat
python turn_extractor.py snapshots_8_119.dat
python turn_extractor.py snapshots_2_26.dat
python turn_extractor.py snapshots_7_169.dat
python turn_extractor.py snapshots_8_150.dat
python turn_extractor.py snapshots_0_186.dat
python turn_extractor.py snapshots_3_202.dat
python turn_extractor.py snapshots_8_24.dat
python turn_extractor.py snapshots_0_240.dat
python turn_extractor.py snapshots_6_102.dat
python turn_extractor.py snapshots_3_48.dat
python turn_extractor.py snapshots_6_60.dat
python turn_extractor.py snapshots_3_99.dat
python turn_extractor.py snapshots_0_291.dat
python turn_extractor.py snapshots_5_191.dat
python turn_extractor.py snapshots_8_247.dat
python turn_extractor.py snapshots_4_92.dat
python turn_extractor.py snapshots_0_157.dat
python turn_extractor.py snapshots_6_215.dat
python turn_extractor.py snapshots_3_115.dat
python turn_extractor.py snapshots_8_181.dat
python turn_extractor.py snapshots_9_196.dat
python turn_extractor.py snapshots_2_102.dat
python turn_extractor.py snapshots_7_7.dat
python turn_extractor.py snapshots_5_51.dat
python turn_extractor.py snapshots_9_36.dat
python turn_extractor.py snapshots_0_79.dat
python turn_extractor.py snapshots_5_80.dat
python turn_extractor.py snapshots_9_147.dat
python turn_extractor.py snapshots_3_34.dat
python turn_extractor.py snapshots_8_58.dat
python turn_extractor.py snapshots_8_89.dat
python turn_extractor.py snapshots_1_17.dat
python turn_extractor.py snapshots_3_169.dat
python turn_extractor.py snapshots_2_105.dat
python turn_extractor.py snapshots_9_191.dat
python turn_extractor.py snapshots_5_56.dat
python turn_extractor.py snapshots_9_31.dat
python turn_extractor.py snapshots_9_257.dat
python turn_extractor.py snapshots_5_87.dat
python turn_extractor.py snapshots_9_140.dat
python turn_extractor.py snapshots_7_75.dat
python turn_extractor.py snapshots_6_179.dat
python turn_extractor.py snapshots_3_33.dat
python turn_extractor.py snapshots_1_10.dat
python turn_extractor.py snapshots_2_21.dat
python turn_extractor.py snapshots_8_157.dat
python turn_extractor.py snapshots_0_181.dat
python turn_extractor.py snapshots_8_291.dat
python turn_extractor.py snapshots_8_23.dat
python turn_extractor.py snapshots_5_147.dat
python turn_extractor.py snapshots_3_205.dat
python turn_extractor.py snapshots_6_105.dat
python turn_extractor.py snapshots_0_247.dat
python turn_extractor.py snapshots_0_296.dat
python turn_extractor.py snapshots_6_67.dat
python turn_extractor.py snapshots_4_95.dat
python turn_extractor.py snapshots_8_240.dat
python turn_extractor.py snapshots_5_196.dat
python turn_extractor.py snapshots_6_212.dat
python turn_extractor.py snapshots_0_150.dat
python turn_extractor.py snapshots_8_186.dat
python turn_extractor.py snapshots_3_112.dat
python turn_extractor.py snapshots_5_58.dat
python turn_extractor.py snapshots_2_53.dat
python turn_extractor.py snapshots_9_259.dat
python turn_extractor.py snapshots_2_82.dat
python turn_extractor.py snapshots_5_89.dat
python turn_extractor.py snapshots_0_70.dat
python turn_extractor.py snapshots_8_125.dat
python turn_extractor.py snapshots_5_135.dat
python turn_extractor.py snapshots_8_51.dat
python turn_extractor.py snapshots_0_235.dat
python turn_extractor.py snapshots_6_177.dat
python turn_extractor.py snapshots_6_15.dat
python turn_extractor.py snapshots_8_232.dat
python turn_extractor.py snapshots_8_80.dat
python turn_extractor.py snapshots_0_122.dat
python turn_extractor.py snapshots_6_260.dat
python turn_extractor.py snapshots_3_160.dat
python turn_extractor.py snapshots_9_43.dat
python turn_extractor.py snapshots_5_24.dat
python turn_extractor.py snapshots_9_225.dat
python turn_extractor.py snapshots_7_160.dat
python turn_extractor.py snapshots_4_122.dat
python turn_extractor.py snapshots_0_4.dat
python turn_extractor.py snapshots_9_92.dat
python turn_extractor.py snapshots_9_132.dat
python turn_extractor.py snapshots_8_159.dat
python turn_extractor.py snapshots_0_249.dat
python turn_extractor.py snapshots_3_41.dat
python turn_extractor.py snapshots_5_149.dat
python turn_extractor.py snapshots_5_198.dat
python turn_extractor.py snapshots_3_90.dat
python turn_extractor.py snapshots_6_69.dat
python turn_extractor.py snapshots_0_298.dat
python turn_extractor.py snapshots_8_188.dat
python turn_extractor.py snapshots_2_28.dat
python turn_extractor.py snapshots_2_170.dat
python turn_extractor.py snapshots_9_44.dat
python turn_extractor.py snapshots_5_23.dat
python turn_extractor.py snapshots_9_222.dat
python turn_extractor.py snapshots_7_167.dat
python turn_extractor.py snapshots_4_125.dat
python turn_extractor.py snapshots_9_95.dat
python turn_extractor.py snapshots_0_3.dat
python turn_extractor.py snapshots_9_135.dat
python turn_extractor.py snapshots_0_188.dat
python turn_extractor.py snapshots_3_46.dat
python turn_extractor.py snapshots_8_249.dat
python turn_extractor.py snapshots_3_97.dat
python turn_extractor.py snapshots_0_159.dat
python turn_extractor.py snapshots_7_9.dat
python turn_extractor.py snapshots_9_38.dat
python turn_extractor.py snapshots_2_54.dat
python turn_extractor.py snapshots_9_198.dat
python turn_extractor.py snapshots_9_149.dat
python turn_extractor.py snapshots_2_85.dat
python turn_extractor.py snapshots_0_77.dat
python turn_extractor.py snapshots_8_122.dat
python turn_extractor.py snapshots_8_56.dat
python turn_extractor.py snapshots_5_132.dat
python turn_extractor.py snapshots_3_270.dat
python turn_extractor.py snapshots_6_170.dat
python turn_extractor.py snapshots_0_232.dat
python turn_extractor.py snapshots_6_12.dat
python turn_extractor.py snapshots_8_87.dat
python turn_extractor.py snapshots_1_19.dat
python turn_extractor.py snapshots_0_125.dat
python turn_extractor.py snapshots_3_167.dat
python turn_extractor.py snapshots_3_86.dat
python turn_extractor.py snapshots_8_258.dat
python turn_extractor.py snapshots_1_74.dat
python turn_extractor.py snapshots_0_148.dat
python turn_extractor.py snapshots_0_199.dat
python turn_extractor.py snapshots_3_57.dat
python turn_extractor.py snapshots_8_1.dat
python turn_extractor.py snapshots_9_124.dat
python turn_extractor.py snapshots_7_11.dat
python turn_extractor.py snapshots_9_84.dat
python turn_extractor.py snapshots_9_55.dat
python turn_extractor.py snapshots_5_32.dat
python turn_extractor.py snapshots_2_39.dat
python turn_extractor.py snapshots_3_5.dat
python turn_extractor.py snapshots_9_233.dat
python turn_extractor.py snapshots_8_224.dat
python turn_extractor.py snapshots_8_96.dat
python turn_extractor.py snapshots_3_176.dat
python turn_extractor.py snapshots_0_134.dat
python turn_extractor.py snapshots_8_133.dat
python turn_extractor.py snapshots_6_161.dat
python turn_extractor.py snapshots_0_223.dat
python turn_extractor.py snapshots_5_123.dat
python turn_extractor.py snapshots_8_47.dat
python turn_extractor.py snapshots_4_20.dat
python turn_extractor.py snapshots_3_261.dat
python turn_extractor.py snapshots_9_158.dat
python turn_extractor.py snapshots_2_94.dat
python turn_extractor.py snapshots_2_45.dat
python turn_extractor.py snapshots_9_189.dat
python turn_extractor.py snapshots_9_29.dat
python turn_extractor.py snapshots_8_223.dat
python turn_extractor.py snapshots_8_91.dat
python turn_extractor.py snapshots_3_171.dat
python turn_extractor.py snapshots_0_133.dat
python turn_extractor.py snapshots_8_134.dat
python turn_extractor.py snapshots_0_224.dat
python turn_extractor.py snapshots_6_166.dat
python turn_extractor.py snapshots_3_266.dat
python turn_extractor.py snapshots_8_40.dat
python turn_extractor.py snapshots_5_124.dat
python turn_extractor.py snapshots_4_8.dat
python turn_extractor.py snapshots_0_61.dat
python turn_extractor.py snapshots_5_98.dat
python turn_extractor.py snapshots_2_93.dat
python turn_extractor.py snapshots_2_42.dat
python turn_extractor.py snapshots_5_49.dat
python turn_extractor.py snapshots_9_248.dat
python turn_extractor.py snapshots_6_78.dat
python turn_extractor.py snapshots_3_81.dat
python turn_extractor.py snapshots_0_289.dat
python turn_extractor.py snapshots_1_73.dat
python turn_extractor.py snapshots_5_189.dat
python turn_extractor.py snapshots_8_199.dat
python turn_extractor.py snapshots_8_148.dat
python turn_extractor.py snapshots_3_50.dat
python turn_extractor.py snapshots_7_171.dat
python turn_extractor.py snapshots_8_6.dat
python turn_extractor.py snapshots_7_16.dat
python turn_extractor.py snapshots_9_123.dat
python turn_extractor.py snapshots_9_83.dat
python turn_extractor.py snapshots_9_52.dat
python turn_extractor.py snapshots_5_35.dat
python turn_extractor.py snapshots_2_166.dat
python turn_extractor.py snapshots_3_2.dat
python turn_extractor.py snapshots_9_234.dat
python turn_extractor.py snapshots_3_268.dat
python turn_extractor.py snapshots_3_22.dat
python turn_extractor.py snapshots_6_168.dat
python turn_extractor.py snapshots_4_6.dat
python turn_extractor.py snapshots_7_103.dat
python turn_extractor.py snapshots_9_151.dat
python turn_extractor.py snapshots_5_96.dat
python turn_extractor.py snapshots_5_47.dat
python turn_extractor.py snapshots_9_20.dat
python turn_extractor.py snapshots_2_114.dat
python turn_extractor.py snapshots_9_180.dat
python turn_extractor.py snapshots_9_246.dat
python turn_extractor.py snapshots_5_187.dat
python turn_extractor.py snapshots_4_84.dat
python turn_extractor.py snapshots_8_251.dat
python turn_extractor.py snapshots_0_287.dat
python turn_extractor.py snapshots_6_76.dat
python turn_extractor.py snapshots_8_197.dat
python turn_extractor.py snapshots_3_103.dat
python turn_extractor.py snapshots_0_141.dat
python turn_extractor.py snapshots_0_190.dat
python turn_extractor.py snapshots_8_146.dat
python turn_extractor.py snapshots_6_114.dat
python turn_extractor.py snapshots_0_256.dat
python turn_extractor.py snapshots_5_156.dat
python turn_extractor.py snapshots_4_55.dat
python turn_extractor.py snapshots_8_280.dat
python turn_extractor.py snapshots_8_32.dat
python turn_extractor.py snapshots_3_214.dat
python turn_extractor.py snapshots_8_8.dat
python turn_extractor.py snapshots_0_13.dat
python turn_extractor.py snapshots_7_18.dat
python turn_extractor.py snapshots_2_168.dat
python turn_extractor.py snapshots_2_30.dat
python turn_extractor.py snapshots_8_256.dat
python turn_extractor.py snapshots_4_83.dat
python turn_extractor.py snapshots_3_88.dat
python turn_extractor.py snapshots_6_71.dat
python turn_extractor.py snapshots_0_280.dat
python turn_extractor.py snapshots_3_104.dat
python turn_extractor.py snapshots_8_190.dat
python turn_extractor.py snapshots_0_146.dat
python turn_extractor.py snapshots_0_197.dat
python turn_extractor.py snapshots_8_141.dat
python turn_extractor.py snapshots_0_251.dat
python turn_extractor.py snapshots_3_59.dat
python turn_extractor.py snapshots_6_113.dat
python turn_extractor.py snapshots_3_213.dat
python turn_extractor.py snapshots_4_52.dat
python turn_extractor.py snapshots_8_35.dat
python turn_extractor.py snapshots_5_151.dat
python turn_extractor.py snapshots_0_14.dat
python turn_extractor.py snapshots_2_37.dat
python turn_extractor.py snapshots_8_98.dat
python turn_extractor.py snapshots_3_178.dat
python turn_extractor.py snapshots_8_49.dat
python turn_extractor.py snapshots_3_25.dat
python turn_extractor.py snapshots_2_204.dat
python turn_extractor.py snapshots_4_1.dat
python turn_extractor.py snapshots_9_156.dat
python turn_extractor.py snapshots_5_91.dat
python turn_extractor.py snapshots_5_40.dat
python turn_extractor.py snapshots_9_27.dat
python turn_extractor.py snapshots_9_187.dat
python turn_extractor.py snapshots_2_113.dat
python turn_extractor.py snapshots_9_241.dat
python turn_extractor.py snapshots_6_95.dat
python turn_extractor.py snapshots_6_126.dat
python turn_extractor.py snapshots_3_226.dat
python turn_extractor.py snapshots_4_67.dat
python turn_extractor.py snapshots_8_174.dat
python turn_extractor.py snapshots_3_131.dat
python turn_extractor.py snapshots_0_173.dat
python turn_extractor.py snapshots_6_231.dat
python turn_extractor.py snapshots_8_263.dat
python turn_extractor.py snapshots_6_7.dat
python turn_extractor.py snapshots_6_44.dat
python turn_extractor.py snapshots_9_208.dat
python turn_extractor.py snapshots_0_21.dat
python turn_extractor.py snapshots_5_118.dat
python turn_extractor.py snapshots_0_218.dat
python turn_extractor.py snapshots_3_10.dat
python turn_extractor.py snapshots_8_108.dat
python turn_extractor.py snapshots_6_38.dat
python turn_extractor.py snapshots_1_33.dat
python turn_extractor.py snapshots_9_274.dat
python turn_extractor.py snapshots_9_12.dat
python turn_extractor.py snapshots_5_75.dat
python turn_extractor.py snapshots_7_87.dat
python turn_extractor.py snapshots_2_126.dat
python turn_extractor.py snapshots_7_56.dat
python turn_extractor.py snapshots_9_163.dat
python turn_extractor.py snapshots_3_17.dat
python turn_extractor.py snapshots_0_108.dat
python turn_extractor.py snapshots_1_34.dat
python turn_extractor.py snapshots_8_218.dat
python turn_extractor.py snapshots_9_273.dat
python turn_extractor.py snapshots_9_15.dat
python turn_extractor.py snapshots_5_72.dat
python turn_extractor.py snapshots_2_79.dat
python turn_extractor.py snapshots_2_121.dat
python turn_extractor.py snapshots_7_80.dat
python turn_extractor.py snapshots_9_164.dat
python turn_extractor.py snapshots_7_136.dat
python turn_extractor.py snapshots_6_92.dat
python turn_extractor.py snapshots_6_121.dat
python turn_extractor.py snapshots_4_60.dat
python turn_extractor.py snapshots_3_221.dat
python turn_extractor.py snapshots_8_173.dat
python turn_extractor.py snapshots_3_136.dat
python turn_extractor.py snapshots_6_236.dat
python turn_extractor.py snapshots_0_174.dat
python turn_extractor.py snapshots_8_264.dat
python turn_extractor.py snapshots_1_48.dat
python turn_extractor.py snapshots_6_43.dat
python turn_extractor.py snapshots_9_69.dat
python turn_extractor.py snapshots_0_26.dat
python turn_extractor.py snapshots_9_118.dat
python turn_extractor.py snapshots_4_108.dat
python turn_extractor.py snapshots_0_211.dat
python turn_extractor.py snapshots_6_153.dat
python turn_extractor.py snapshots_3_19.dat
python turn_extractor.py snapshots_1_4.dat
python turn_extractor.py snapshots_3_253.dat
python turn_extractor.py snapshots_5_111.dat
python turn_extractor.py snapshots_4_12.dat
python turn_extractor.py snapshots_8_75.dat
python turn_extractor.py snapshots_8_101.dat
python turn_extractor.py snapshots_3_195.dat
python turn_extractor.py snapshots_3_144.dat
python turn_extractor.py snapshots_5_206.dat
python turn_extractor.py snapshots_0_106.dat
python turn_extractor.py snapshots_6_244.dat
python turn_extractor.py snapshots_8_216.dat
python turn_extractor.py snapshots_6_31.dat
python turn_extractor.py snapshots_6_182.dat
python turn_extractor.py snapshots_2_77.dat
python turn_extractor.py snapshots_0_85.dat
python turn_extractor.py snapshots_0_54.dat
python turn_extractor.py snapshots_7_138.dat
python turn_extractor.py snapshots_3_65.dat
python turn_extractor.py snapshots_6_238.dat
python turn_extractor.py snapshots_3_138.dat
python turn_extractor.py snapshots_1_46.dat
python turn_extractor.py snapshots_9_201.dat
python turn_extractor.py snapshots_9_67.dat
python turn_extractor.py snapshots_2_153.dat
python turn_extractor.py snapshots_7_23.dat
python turn_extractor.py snapshots_2_182.dat
python turn_extractor.py snapshots_9_116.dat
python turn_extractor.py snapshots_0_28.dat
python turn_extractor.py snapshots_4_106.dat
python turn_extractor.py snapshots_4_69.dat
python turn_extractor.py snapshots_3_228.dat
python turn_extractor.py snapshots_6_128.dat
python turn_extractor.py snapshots_3_62.dat
python turn_extractor.py snapshots_6_9.dat
python turn_extractor.py snapshots_1_41.dat
python turn_extractor.py snapshots_9_206.dat
python turn_extractor.py snapshots_9_60.dat
python turn_extractor.py snapshots_2_154.dat
python turn_extractor.py snapshots_9_111.dat
python turn_extractor.py snapshots_2_185.dat
python turn_extractor.py snapshots_7_24.dat
python turn_extractor.py snapshots_4_101.dat
python turn_extractor.py snapshots_6_154.dat
python turn_extractor.py snapshots_0_216.dat
python turn_extractor.py snapshots_4_15.dat
python turn_extractor.py snapshots_8_72.dat
python turn_extractor.py snapshots_5_116.dat
python turn_extractor.py snapshots_3_254.dat
python turn_extractor.py snapshots_3_192.dat
python turn_extractor.py snapshots_8_106.dat
python turn_extractor.py snapshots_5_201.dat
python turn_extractor.py snapshots_3_143.dat
python turn_extractor.py snapshots_6_243.dat
python turn_extractor.py snapshots_0_101.dat
python turn_extractor.py snapshots_8_211.dat
python turn_extractor.py snapshots_6_36.dat
python turn_extractor.py snapshots_6_185.dat
python turn_extractor.py snapshots_7_89.dat
python turn_extractor.py snapshots_2_128.dat
python turn_extractor.py snapshots_2_70.dat
python turn_extractor.py snapshots_0_82.dat
python turn_extractor.py snapshots_0_53.dat
python turn_extractor.py snapshots_7_58.dat
python turn_extractor.py snapshots_5_22.dat
python turn_extractor.py snapshots_9_45.dat
python turn_extractor.py snapshots_2_171.dat
python turn_extractor.py snapshots_2_29.dat
python turn_extractor.py snapshots_9_223.dat
python turn_extractor.py snapshots_4_124.dat
python turn_extractor.py snapshots_7_166.dat
python turn_extractor.py snapshots_9_134.dat
python turn_extractor.py snapshots_9_94.dat
python turn_extractor.py snapshots_0_2.dat
python turn_extractor.py snapshots_0_189.dat
python turn_extractor.py snapshots_3_47.dat
python turn_extractor.py snapshots_3_96.dat
python turn_extractor.py snapshots_8_248.dat
python turn_extractor.py snapshots_0_158.dat
python turn_extractor.py snapshots_2_55.dat
python turn_extractor.py snapshots_9_199.dat
python turn_extractor.py snapshots_9_39.dat
python turn_extractor.py snapshots_7_8.dat
python turn_extractor.py snapshots_0_76.dat
python turn_extractor.py snapshots_9_148.dat
python turn_extractor.py snapshots_2_84.dat
python turn_extractor.py snapshots_8_123.dat
python turn_extractor.py snapshots_6_171.dat
python turn_extractor.py snapshots_0_233.dat
python turn_extractor.py snapshots_5_133.dat
python turn_extractor.py snapshots_8_57.dat
python turn_extractor.py snapshots_1_18.dat
python turn_extractor.py snapshots_8_86.dat
python turn_extractor.py snapshots_6_13.dat
python turn_extractor.py snapshots_3_166.dat
python turn_extractor.py snapshots_6_266.dat
python turn_extractor.py snapshots_0_124.dat
python turn_extractor.py snapshots_2_52.dat
python turn_extractor.py snapshots_5_59.dat
python turn_extractor.py snapshots_9_258.dat
python turn_extractor.py snapshots_0_71.dat
python turn_extractor.py snapshots_5_88.dat
python turn_extractor.py snapshots_2_83.dat
python turn_extractor.py snapshots_8_124.dat
python turn_extractor.py snapshots_0_234.dat
python turn_extractor.py snapshots_6_176.dat
python turn_extractor.py snapshots_8_50.dat
python turn_extractor.py snapshots_5_134.dat
python turn_extractor.py snapshots_8_81.dat
python turn_extractor.py snapshots_6_14.dat
python turn_extractor.py snapshots_3_161.dat
python turn_extractor.py snapshots_0_123.dat
python turn_extractor.py snapshots_6_261.dat
python turn_extractor.py snapshots_5_25.dat
python turn_extractor.py snapshots_9_42.dat
python turn_extractor.py snapshots_9_224.dat
python turn_extractor.py snapshots_4_123.dat
python turn_extractor.py snapshots_7_161.dat
python turn_extractor.py snapshots_9_133.dat
python turn_extractor.py snapshots_0_5.dat
python turn_extractor.py snapshots_9_93.dat
python turn_extractor.py snapshots_8_158.dat
python turn_extractor.py snapshots_5_148.dat
python turn_extractor.py snapshots_0_248.dat
python turn_extractor.py snapshots_3_40.dat
python turn_extractor.py snapshots_6_68.dat
python turn_extractor.py snapshots_3_91.dat
python turn_extractor.py snapshots_5_199.dat
python turn_extractor.py snapshots_8_189.dat
python turn_extractor.py snapshots_7_1.dat
python turn_extractor.py snapshots_9_30.dat
python turn_extractor.py snapshots_5_57.dat
python turn_extractor.py snapshots_2_104.dat
python turn_extractor.py snapshots_9_190.dat
python turn_extractor.py snapshots_9_256.dat
python turn_extractor.py snapshots_9_141.dat
python turn_extractor.py snapshots_5_86.dat
python turn_extractor.py snapshots_3_32.dat
python turn_extractor.py snapshots_6_178.dat
python turn_extractor.py snapshots_1_11.dat
python turn_extractor.py snapshots_2_20.dat
python turn_extractor.py snapshots_0_180.dat
python turn_extractor.py snapshots_8_156.dat
python turn_extractor.py snapshots_6_104.dat
python turn_extractor.py snapshots_0_246.dat
python turn_extractor.py snapshots_5_146.dat
python turn_extractor.py snapshots_8_22.dat
python turn_extractor.py snapshots_8_290.dat
python turn_extractor.py snapshots_3_204.dat
python turn_extractor.py snapshots_5_197.dat
python turn_extractor.py snapshots_4_94.dat
python turn_extractor.py snapshots_8_241.dat
python turn_extractor.py snapshots_0_297.dat
python turn_extractor.py snapshots_6_66.dat
python turn_extractor.py snapshots_8_187.dat
python turn_extractor.py snapshots_3_113.dat
python turn_extractor.py snapshots_6_213.dat
python turn_extractor.py snapshots_0_151.dat
python turn_extractor.py snapshots_2_27.dat
python turn_extractor.py snapshots_7_168.dat
python turn_extractor.py snapshots_0_187.dat
python turn_extractor.py snapshots_8_151.dat
python turn_extractor.py snapshots_0_241.dat
python turn_extractor.py snapshots_3_49.dat
python turn_extractor.py snapshots_6_103.dat
python turn_extractor.py snapshots_3_203.dat
python turn_extractor.py snapshots_8_25.dat
python turn_extractor.py snapshots_5_141.dat
python turn_extractor.py snapshots_8_246.dat
python turn_extractor.py snapshots_4_93.dat
python turn_extractor.py snapshots_5_190.dat
python turn_extractor.py snapshots_3_98.dat
python turn_extractor.py snapshots_6_61.dat
python turn_extractor.py snapshots_0_290.dat
python turn_extractor.py snapshots_3_114.dat
python turn_extractor.py snapshots_8_180.dat
python turn_extractor.py snapshots_0_156.dat
python turn_extractor.py snapshots_6_214.dat
python turn_extractor.py snapshots_9_37.dat
python turn_extractor.py snapshots_5_50.dat
python turn_extractor.py snapshots_7_6.dat
python turn_extractor.py snapshots_9_197.dat
python turn_extractor.py snapshots_2_103.dat
python turn_extractor.py snapshots_9_146.dat
python turn_extractor.py snapshots_5_81.dat
python turn_extractor.py snapshots_0_78.dat
python turn_extractor.py snapshots_8_59.dat
python turn_extractor.py snapshots_3_35.dat
python turn_extractor.py snapshots_1_16.dat
python turn_extractor.py snapshots_8_88.dat
python turn_extractor.py snapshots_3_168.dat
python turn_extractor.py snapshots_0_31.dat
python turn_extractor.py snapshots_9_218.dat
python turn_extractor.py snapshots_2_12.dat
python turn_extractor.py snapshots_5_19.dat
python turn_extractor.py snapshots_3_121.dat
python turn_extractor.py snapshots_0_163.dat
python turn_extractor.py snapshots_6_221.dat
python turn_extractor.py snapshots_8_273.dat
python turn_extractor.py snapshots_6_54.dat
python turn_extractor.py snapshots_0_274.dat
python turn_extractor.py snapshots_6_136.dat
python turn_extractor.py snapshots_6_85.dat
python turn_extractor.py snapshots_3_236.dat
python turn_extractor.py snapshots_4_77.dat
python turn_extractor.py snapshots_8_10.dat
python turn_extractor.py snapshots_8_164.dat
python turn_extractor.py snapshots_7_46.dat
python turn_extractor.py snapshots_9_173.dat
python turn_extractor.py snapshots_9_264.dat
python turn_extractor.py snapshots_5_65.dat
python turn_extractor.py snapshots_2_136.dat
python turn_extractor.py snapshots_6_28.dat
python turn_extractor.py snapshots_5_108.dat
python turn_extractor.py snapshots_0_208.dat
python turn_extractor.py snapshots_8_118.dat
python turn_extractor.py snapshots_9_174.dat
python turn_extractor.py snapshots_7_41.dat
python turn_extractor.py snapshots_9_263.dat
python turn_extractor.py snapshots_5_62.dat
python turn_extractor.py snapshots_2_131.dat
python turn_extractor.py snapshots_2_69.dat
python turn_extractor.py snapshots_7_90.dat
python turn_extractor.py snapshots_0_118.dat
python turn_extractor.py snapshots_5_218.dat
python turn_extractor.py snapshots_8_208.dat
python turn_extractor.py snapshots_9_9.dat
python turn_extractor.py snapshots_0_36.dat
python turn_extractor.py snapshots_9_108.dat
python turn_extractor.py snapshots_2_15.dat
python turn_extractor.py snapshots_9_79.dat
python turn_extractor.py snapshots_3_126.dat
python turn_extractor.py snapshots_6_226.dat
python turn_extractor.py snapshots_0_164.dat
python turn_extractor.py snapshots_8_274.dat
python turn_extractor.py snapshots_6_53.dat
python turn_extractor.py snapshots_6_131.dat
python turn_extractor.py snapshots_6_82.dat
python turn_extractor.py snapshots_0_273.dat
python turn_extractor.py snapshots_4_70.dat
python turn_extractor.py snapshots_8_17.dat
python turn_extractor.py snapshots_3_231.dat
python turn_extractor.py snapshots_5_7.dat
python turn_extractor.py snapshots_8_163.dat
python turn_extractor.py snapshots_0_44.dat
python turn_extractor.py snapshots_2_67.dat
python turn_extractor.py snapshots_0_95.dat
python turn_extractor.py snapshots_2_3.dat
python turn_extractor.py snapshots_3_154.dat
python turn_extractor.py snapshots_5_216.dat
python turn_extractor.py snapshots_0_116.dat
python turn_extractor.py snapshots_6_254.dat
python turn_extractor.py snapshots_8_206.dat
python turn_extractor.py snapshots_6_192.dat
python turn_extractor.py snapshots_6_21.dat
python turn_extractor.py snapshots_0_201.dat
python turn_extractor.py snapshots_6_143.dat
python turn_extractor.py snapshots_5_101.dat
python turn_extractor.py snapshots_8_65.dat
python turn_extractor.py snapshots_6_285.dat
python turn_extractor.py snapshots_8_111.dat
python turn_extractor.py snapshots_9_7.dat
python turn_extractor.py snapshots_3_185.dat
python turn_extractor.py snapshots_7_33.dat
python turn_extractor.py snapshots_9_106.dat
python turn_extractor.py snapshots_0_38.dat
python turn_extractor.py snapshots_4_116.dat
python turn_extractor.py snapshots_7_154.dat
python turn_extractor.py snapshots_9_211.dat
python turn_extractor.py snapshots_9_77.dat
python turn_extractor.py snapshots_5_10.dat
python turn_extractor.py snapshots_2_143.dat
python turn_extractor.py snapshots_6_228.dat
python turn_extractor.py snapshots_3_128.dat
python turn_extractor.py snapshots_8_19.dat
python turn_extractor.py snapshots_3_75.dat
python turn_extractor.py snapshots_5_9.dat
python turn_extractor.py snapshots_9_101.dat
python turn_extractor.py snapshots_7_34.dat
python turn_extractor.py snapshots_7_153.dat
python turn_extractor.py snapshots_9_216.dat
python turn_extractor.py snapshots_9_70.dat
python turn_extractor.py snapshots_5_17.dat
python turn_extractor.py snapshots_2_144.dat
python turn_extractor.py snapshots_4_79.dat
python turn_extractor.py snapshots_3_238.dat
python turn_extractor.py snapshots_6_138.dat
python turn_extractor.py snapshots_3_72.dat
python turn_extractor.py snapshots_0_43.dat
python turn_extractor.py snapshots_7_48.dat
python turn_extractor.py snapshots_7_99.dat
python turn_extractor.py snapshots_2_60.dat
python turn_extractor.py snapshots_2_138.dat
python turn_extractor.py snapshots_0_92.dat
python turn_extractor.py snapshots_2_4.dat
python turn_extractor.py snapshots_3_153.dat
python turn_extractor.py snapshots_6_253.dat
python turn_extractor.py snapshots_0_111.dat
python turn_extractor.py snapshots_8_201.dat
python turn_extractor.py snapshots_6_195.dat
python turn_extractor.py snapshots_6_26.dat
python turn_extractor.py snapshots_6_144.dat
python turn_extractor.py snapshots_0_206.dat
python turn_extractor.py snapshots_8_62.dat
python turn_extractor.py snapshots_5_106.dat
python turn_extractor.py snapshots_6_282.dat
python turn_extractor.py snapshots_3_182.dat
python turn_extractor.py snapshots_8_116.dat
python turn_extractor.py snapshots_3_63.dat
python turn_extractor.py snapshots_6_129.dat
python turn_extractor.py snapshots_4_68.dat
python turn_extractor.py snapshots_3_229.dat
python turn_extractor.py snapshots_6_8.dat
python turn_extractor.py snapshots_1_40.dat
python turn_extractor.py snapshots_9_207.dat
python turn_extractor.py snapshots_2_155.dat
python turn_extractor.py snapshots_9_61.dat
python turn_extractor.py snapshots_9_110.dat
python turn_extractor.py snapshots_7_25.dat
python turn_extractor.py snapshots_2_184.dat
python turn_extractor.py snapshots_4_100.dat
python turn_extractor.py snapshots_5_117.dat
python turn_extractor.py snapshots_8_73.dat
python turn_extractor.py snapshots_4_14.dat
python turn_extractor.py snapshots_3_255.dat
python turn_extractor.py snapshots_6_155.dat
python turn_extractor.py snapshots_0_217.dat
python turn_extractor.py snapshots_3_193.dat
python turn_extractor.py snapshots_8_107.dat
python turn_extractor.py snapshots_6_242.dat
python turn_extractor.py snapshots_0_100.dat
python turn_extractor.py snapshots_5_200.dat
python turn_extractor.py snapshots_3_142.dat
python turn_extractor.py snapshots_6_184.dat
python turn_extractor.py snapshots_6_37.dat
python turn_extractor.py snapshots_8_210.dat
python turn_extractor.py snapshots_0_83.dat
python turn_extractor.py snapshots_2_71.dat
python turn_extractor.py snapshots_2_129.dat
python turn_extractor.py snapshots_7_88.dat
python turn_extractor.py snapshots_7_59.dat
python turn_extractor.py snapshots_0_52.dat
python turn_extractor.py snapshots_3_252.dat
python turn_extractor.py snapshots_1_5.dat
python turn_extractor.py snapshots_8_74.dat
python turn_extractor.py snapshots_4_13.dat
python turn_extractor.py snapshots_5_110.dat
python turn_extractor.py snapshots_0_210.dat
python turn_extractor.py snapshots_3_18.dat
python turn_extractor.py snapshots_6_152.dat
python turn_extractor.py snapshots_8_100.dat
python turn_extractor.py snapshots_3_194.dat
python turn_extractor.py snapshots_0_107.dat
python turn_extractor.py snapshots_6_245.dat
python turn_extractor.py snapshots_3_145.dat
python turn_extractor.py snapshots_6_183.dat
python turn_extractor.py snapshots_6_30.dat
python turn_extractor.py snapshots_8_217.dat
python turn_extractor.py snapshots_0_84.dat
python turn_extractor.py snapshots_2_76.dat
python turn_extractor.py snapshots_0_55.dat
python turn_extractor.py snapshots_3_64.dat
python turn_extractor.py snapshots_3_139.dat
python turn_extractor.py snapshots_6_239.dat
python turn_extractor.py snapshots_1_47.dat
python turn_extractor.py snapshots_9_200.dat
python turn_extractor.py snapshots_2_152.dat
python turn_extractor.py snapshots_9_66.dat
python turn_extractor.py snapshots_0_29.dat
python turn_extractor.py snapshots_2_183.dat
python turn_extractor.py snapshots_7_22.dat
python turn_extractor.py snapshots_9_117.dat
python turn_extractor.py snapshots_4_107.dat
python turn_extractor.py snapshots_3_16.dat
python turn_extractor.py snapshots_0_109.dat
python turn_extractor.py snapshots_8_219.dat
python turn_extractor.py snapshots_1_35.dat
python turn_extractor.py snapshots_9_272.dat
python turn_extractor.py snapshots_7_81.dat
python turn_extractor.py snapshots_2_120.dat
python turn_extractor.py snapshots_2_78.dat
python turn_extractor.py snapshots_5_73.dat
python turn_extractor.py snapshots_9_14.dat
python turn_extractor.py snapshots_9_165.dat
python turn_extractor.py snapshots_7_137.dat
python turn_extractor.py snapshots_4_61.dat
python turn_extractor.py snapshots_3_220.dat
python turn_extractor.py snapshots_6_120.dat
python turn_extractor.py snapshots_6_93.dat
python turn_extractor.py snapshots_8_172.dat
python turn_extractor.py snapshots_6_237.dat
python turn_extractor.py snapshots_0_175.dat
python turn_extractor.py snapshots_3_137.dat
python turn_extractor.py snapshots_6_42.dat
python turn_extractor.py snapshots_6_1.dat
python turn_extractor.py snapshots_1_49.dat
python turn_extractor.py snapshots_8_265.dat
python turn_extractor.py snapshots_9_68.dat
python turn_extractor.py snapshots_9_119.dat
python turn_extractor.py snapshots_0_27.dat
python turn_extractor.py snapshots_4_109.dat
python turn_extractor.py snapshots_3_227.dat
python turn_extractor.py snapshots_4_66.dat
python turn_extractor.py snapshots_6_127.dat
python turn_extractor.py snapshots_6_94.dat
python turn_extractor.py snapshots_8_175.dat
python turn_extractor.py snapshots_0_172.dat
python turn_extractor.py snapshots_6_230.dat
python turn_extractor.py snapshots_3_130.dat
python turn_extractor.py snapshots_6_45.dat
python turn_extractor.py snapshots_8_262.dat
python turn_extractor.py snapshots_6_6.dat
python turn_extractor.py snapshots_9_209.dat
python turn_extractor.py snapshots_0_20.dat
python turn_extractor.py snapshots_0_219.dat
python turn_extractor.py snapshots_3_11.dat
python turn_extractor.py snapshots_5_119.dat
python turn_extractor.py snapshots_8_109.dat
python turn_extractor.py snapshots_1_32.dat
python turn_extractor.py snapshots_6_39.dat
python turn_extractor.py snapshots_9_275.dat
python turn_extractor.py snapshots_2_127.dat
python turn_extractor.py snapshots_7_86.dat
python turn_extractor.py snapshots_5_74.dat
python turn_extractor.py snapshots_9_13.dat
python turn_extractor.py snapshots_7_57.dat
python turn_extractor.py snapshots_9_162.dat
python turn_extractor.py snapshots_6_70.dat
python turn_extractor.py snapshots_3_89.dat
python turn_extractor.py snapshots_0_281.dat
python turn_extractor.py snapshots_8_257.dat
python turn_extractor.py snapshots_4_82.dat
python turn_extractor.py snapshots_0_147.dat
python turn_extractor.py snapshots_3_105.dat
python turn_extractor.py snapshots_8_191.dat
python turn_extractor.py snapshots_8_140.dat
python turn_extractor.py snapshots_0_196.dat
python turn_extractor.py snapshots_3_212.dat
python turn_extractor.py snapshots_5_150.dat
python turn_extractor.py snapshots_8_34.dat
python turn_extractor.py snapshots_4_53.dat
python turn_extractor.py snapshots_0_250.dat
python turn_extractor.py snapshots_6_112.dat
python turn_extractor.py snapshots_3_58.dat
python turn_extractor.py snapshots_0_15.dat
python turn_extractor.py snapshots_2_36.dat
python turn_extractor.py snapshots_8_99.dat
python turn_extractor.py snapshots_3_179.dat
python turn_extractor.py snapshots_6_279.dat
python turn_extractor.py snapshots_3_24.dat
python turn_extractor.py snapshots_8_48.dat
python turn_extractor.py snapshots_2_205.dat
python turn_extractor.py snapshots_5_90.dat
python turn_extractor.py snapshots_9_157.dat
python turn_extractor.py snapshots_9_186.dat
python turn_extractor.py snapshots_2_112.dat
python turn_extractor.py snapshots_9_26.dat
python turn_extractor.py snapshots_5_41.dat
python turn_extractor.py snapshots_9_240.dat
python turn_extractor.py snapshots_6_169.dat
python turn_extractor.py snapshots_3_23.dat
python turn_extractor.py snapshots_3_269.dat
python turn_extractor.py snapshots_4_7.dat
python turn_extractor.py snapshots_7_102.dat
python turn_extractor.py snapshots_5_97.dat
python turn_extractor.py snapshots_9_150.dat
python turn_extractor.py snapshots_2_115.dat
python turn_extractor.py snapshots_9_181.dat
python turn_extractor.py snapshots_9_21.dat
python turn_extractor.py snapshots_5_46.dat
python turn_extractor.py snapshots_9_247.dat
python turn_extractor.py snapshots_0_286.dat
python turn_extractor.py snapshots_6_77.dat
python turn_extractor.py snapshots_4_85.dat
python turn_extractor.py snapshots_8_250.dat
python turn_extractor.py snapshots_5_186.dat
python turn_extractor.py snapshots_0_140.dat
python turn_extractor.py snapshots_8_196.dat
python turn_extractor.py snapshots_3_102.dat
python turn_extractor.py snapshots_8_147.dat
python turn_extractor.py snapshots_0_191.dat
python turn_extractor.py snapshots_8_33.dat
python turn_extractor.py snapshots_4_54.dat
python turn_extractor.py snapshots_8_281.dat
python turn_extractor.py snapshots_5_157.dat
python turn_extractor.py snapshots_3_215.dat
python turn_extractor.py snapshots_6_115.dat
python turn_extractor.py snapshots_0_257.dat
python turn_extractor.py snapshots_8_9.dat
python turn_extractor.py snapshots_7_19.dat
python turn_extractor.py snapshots_0_12.dat
python turn_extractor.py snapshots_2_31.dat
python turn_extractor.py snapshots_2_169.dat
python turn_extractor.py snapshots_8_90.dat
python turn_extractor.py snapshots_8_222.dat
python turn_extractor.py snapshots_0_132.dat
python turn_extractor.py snapshots_3_170.dat
python turn_extractor.py snapshots_8_135.dat
python turn_extractor.py snapshots_3_267.dat
python turn_extractor.py snapshots_5_125.dat
python turn_extractor.py snapshots_8_41.dat
python turn_extractor.py snapshots_0_225.dat
python turn_extractor.py snapshots_6_167.dat
python turn_extractor.py snapshots_4_9.dat
python turn_extractor.py snapshots_2_92.dat
python turn_extractor.py snapshots_5_99.dat
python turn_extractor.py snapshots_0_60.dat
python turn_extractor.py snapshots_5_48.dat
python turn_extractor.py snapshots_2_43.dat
python turn_extractor.py snapshots_5_188.dat
python turn_extractor.py snapshots_3_80.dat
python turn_extractor.py snapshots_6_79.dat
python turn_extractor.py snapshots_0_288.dat
python turn_extractor.py snapshots_8_198.dat
python turn_extractor.py snapshots_8_149.dat
python turn_extractor.py snapshots_3_51.dat
python turn_extractor.py snapshots_7_170.dat
python turn_extractor.py snapshots_8_7.dat
python turn_extractor.py snapshots_9_82.dat
python turn_extractor.py snapshots_7_17.dat
python turn_extractor.py snapshots_9_122.dat
python turn_extractor.py snapshots_2_167.dat
python turn_extractor.py snapshots_5_34.dat
python turn_extractor.py snapshots_9_53.dat
python turn_extractor.py snapshots_9_235.dat
python turn_extractor.py snapshots_3_3.dat
python turn_extractor.py snapshots_1_75.dat
python turn_extractor.py snapshots_8_259.dat
python turn_extractor.py snapshots_3_87.dat
python turn_extractor.py snapshots_0_149.dat
python turn_extractor.py snapshots_0_198.dat
python turn_extractor.py snapshots_3_56.dat
python turn_extractor.py snapshots_9_85.dat
python turn_extractor.py snapshots_9_125.dat
python turn_extractor.py snapshots_7_10.dat
python turn_extractor.py snapshots_2_160.dat
python turn_extractor.py snapshots_2_38.dat
python turn_extractor.py snapshots_5_33.dat
python turn_extractor.py snapshots_9_54.dat
python turn_extractor.py snapshots_9_232.dat
python turn_extractor.py snapshots_3_4.dat
python turn_extractor.py snapshots_8_97.dat
python turn_extractor.py snapshots_8_225.dat
python turn_extractor.py snapshots_0_135.dat
python turn_extractor.py snapshots_5_235.dat
python turn_extractor.py snapshots_3_177.dat
python turn_extractor.py snapshots_8_132.dat
python turn_extractor.py snapshots_4_21.dat
python turn_extractor.py snapshots_8_46.dat
python turn_extractor.py snapshots_5_122.dat
python turn_extractor.py snapshots_3_260.dat
python turn_extractor.py snapshots_6_160.dat
python turn_extractor.py snapshots_0_222.dat
python turn_extractor.py snapshots_9_159.dat
python turn_extractor.py snapshots_2_95.dat
python turn_extractor.py snapshots_9_28.dat
python turn_extractor.py snapshots_2_44.dat
python turn_extractor.py snapshots_9_188.dat
python turn_extractor.py snapshots_3_197.dat
python turn_extractor.py snapshots_8_103.dat
python turn_extractor.py snapshots_6_151.dat
python turn_extractor.py snapshots_0_213.dat
python turn_extractor.py snapshots_4_10.dat
python turn_extractor.py snapshots_8_77.dat
python turn_extractor.py snapshots_5_113.dat
python turn_extractor.py snapshots_1_6.dat
python turn_extractor.py snapshots_3_251.dat
python turn_extractor.py snapshots_8_214.dat
python turn_extractor.py snapshots_1_38.dat
python turn_extractor.py snapshots_6_33.dat
python turn_extractor.py snapshots_6_180.dat
python turn_extractor.py snapshots_5_204.dat
python turn_extractor.py snapshots_3_146.dat
python turn_extractor.py snapshots_6_246.dat
python turn_extractor.py snapshots_0_104.dat
python turn_extractor.py snapshots_2_75.dat
python turn_extractor.py snapshots_0_87.dat
python turn_extractor.py snapshots_9_19.dat
python turn_extractor.py snapshots_0_56.dat
python turn_extractor.py snapshots_9_168.dat
python turn_extractor.py snapshots_3_67.dat
python turn_extractor.py snapshots_1_44.dat
python turn_extractor.py snapshots_8_268.dat
python turn_extractor.py snapshots_0_178.dat
python turn_extractor.py snapshots_9_65.dat
python turn_extractor.py snapshots_2_151.dat
python turn_extractor.py snapshots_9_203.dat
python turn_extractor.py snapshots_4_104.dat
python turn_extractor.py snapshots_9_114.dat
python turn_extractor.py snapshots_7_21.dat
python turn_extractor.py snapshots_8_178.dat
python turn_extractor.py snapshots_0_268.dat
python turn_extractor.py snapshots_3_60.dat
python turn_extractor.py snapshots_6_99.dat
python turn_extractor.py snapshots_6_48.dat
python turn_extractor.py snapshots_1_43.dat
python turn_extractor.py snapshots_9_62.dat
python turn_extractor.py snapshots_2_156.dat
python turn_extractor.py snapshots_9_204.dat
python turn_extractor.py snapshots_4_103.dat
python turn_extractor.py snapshots_7_26.dat
python turn_extractor.py snapshots_2_187.dat
python turn_extractor.py snapshots_9_113.dat
python turn_extractor.py snapshots_8_104.dat
python turn_extractor.py snapshots_3_190.dat
python turn_extractor.py snapshots_0_214.dat
python turn_extractor.py snapshots_6_156.dat
python turn_extractor.py snapshots_3_256.dat
python turn_extractor.py snapshots_5_114.dat
python turn_extractor.py snapshots_4_17.dat
python turn_extractor.py snapshots_8_70.dat
python turn_extractor.py snapshots_8_213.dat
python turn_extractor.py snapshots_6_34.dat
python turn_extractor.py snapshots_6_187.dat
python turn_extractor.py snapshots_3_141.dat
python turn_extractor.py snapshots_5_203.dat
python turn_extractor.py snapshots_0_103.dat
python turn_extractor.py snapshots_6_241.dat
python turn_extractor.py snapshots_2_72.dat
python turn_extractor.py snapshots_5_79.dat
python turn_extractor.py snapshots_0_80.dat
python turn_extractor.py snapshots_0_51.dat
python turn_extractor.py snapshots_8_176.dat
python turn_extractor.py snapshots_6_97.dat
python turn_extractor.py snapshots_6_124.dat
python turn_extractor.py snapshots_0_266.dat
python turn_extractor.py snapshots_4_65.dat
python turn_extractor.py snapshots_3_224.dat
python turn_extractor.py snapshots_6_5.dat
python turn_extractor.py snapshots_8_261.dat
python turn_extractor.py snapshots_6_46.dat
python turn_extractor.py snapshots_3_133.dat
python turn_extractor.py snapshots_6_233.dat
python turn_extractor.py snapshots_0_171.dat
python turn_extractor.py snapshots_2_158.dat
python turn_extractor.py snapshots_0_23.dat
python turn_extractor.py snapshots_7_28.dat
python turn_extractor.py snapshots_2_189.dat
python turn_extractor.py snapshots_4_19.dat
python turn_extractor.py snapshots_3_258.dat
python turn_extractor.py snapshots_6_158.dat
python turn_extractor.py snapshots_3_12.dat
python turn_extractor.py snapshots_6_189.dat
python turn_extractor.py snapshots_1_31.dat
python turn_extractor.py snapshots_9_10.dat
python turn_extractor.py snapshots_5_77.dat
python turn_extractor.py snapshots_2_124.dat
python turn_extractor.py snapshots_7_85.dat
python turn_extractor.py snapshots_9_276.dat
python turn_extractor.py snapshots_7_133.dat
python turn_extractor.py snapshots_9_161.dat
python turn_extractor.py snapshots_3_199.dat
python turn_extractor.py snapshots_1_8.dat
python turn_extractor.py snapshots_8_79.dat
python turn_extractor.py snapshots_3_15.dat
python turn_extractor.py snapshots_1_36.dat
python turn_extractor.py snapshots_6_248.dat
python turn_extractor.py snapshots_3_148.dat
python turn_extractor.py snapshots_0_89.dat
python turn_extractor.py snapshots_9_17.dat
python turn_extractor.py snapshots_5_70.dat
python turn_extractor.py snapshots_7_82.dat
python turn_extractor.py snapshots_2_123.dat
python turn_extractor.py snapshots_9_271.dat
python turn_extractor.py snapshots_7_134.dat
python turn_extractor.py snapshots_9_166.dat
python turn_extractor.py snapshots_0_58.dat
python turn_extractor.py snapshots_8_171.dat
python turn_extractor.py snapshots_6_90.dat
python turn_extractor.py snapshots_6_123.dat
python turn_extractor.py snapshots_3_69.dat
python turn_extractor.py snapshots_3_223.dat
python turn_extractor.py snapshots_4_62.dat
python turn_extractor.py snapshots_8_266.dat
python turn_extractor.py snapshots_6_2.dat
python turn_extractor.py snapshots_6_41.dat
python turn_extractor.py snapshots_3_134.dat
python turn_extractor.py snapshots_0_176.dat
python turn_extractor.py snapshots_6_234.dat
python turn_extractor.py snapshots_0_24.dat
python turn_extractor.py snapshots_5_128.dat
python turn_extractor.py snapshots_0_228.dat
python turn_extractor.py snapshots_3_20.dat
python turn_extractor.py snapshots_8_138.dat
python turn_extractor.py snapshots_9_153.dat
python turn_extractor.py snapshots_5_94.dat
python turn_extractor.py snapshots_7_101.dat
python turn_extractor.py snapshots_4_4.dat
python turn_extractor.py snapshots_9_244.dat
python turn_extractor.py snapshots_5_45.dat
python turn_extractor.py snapshots_9_22.dat
python turn_extractor.py snapshots_9_182.dat
python turn_extractor.py snapshots_2_116.dat
python turn_extractor.py snapshots_3_101.dat
python turn_extractor.py snapshots_8_195.dat
python turn_extractor.py snapshots_0_143.dat
python turn_extractor.py snapshots_8_253.dat
python turn_extractor.py snapshots_4_86.dat
python turn_extractor.py snapshots_5_185.dat
python turn_extractor.py snapshots_6_74.dat
python turn_extractor.py snapshots_0_285.dat
python turn_extractor.py snapshots_0_254.dat
python turn_extractor.py snapshots_6_116.dat
python turn_extractor.py snapshots_3_216.dat
python turn_extractor.py snapshots_8_282.dat
python turn_extractor.py snapshots_4_57.dat
python turn_extractor.py snapshots_8_30.dat
python turn_extractor.py snapshots_5_154.dat
python turn_extractor.py snapshots_0_192.dat
python turn_extractor.py snapshots_8_144.dat
python turn_extractor.py snapshots_0_11.dat
python turn_extractor.py snapshots_9_238.dat
python turn_extractor.py snapshots_2_32.dat
python turn_extractor.py snapshots_5_39.dat
python turn_extractor.py snapshots_8_192.dat
python turn_extractor.py snapshots_3_106.dat
python turn_extractor.py snapshots_6_206.dat
python turn_extractor.py snapshots_0_144.dat
python turn_extractor.py snapshots_1_78.dat
python turn_extractor.py snapshots_4_81.dat
python turn_extractor.py snapshots_8_254.dat
python turn_extractor.py snapshots_0_282.dat
python turn_extractor.py snapshots_6_73.dat
python turn_extractor.py snapshots_6_111.dat
python turn_extractor.py snapshots_0_253.dat
python turn_extractor.py snapshots_5_153.dat
python turn_extractor.py snapshots_4_50.dat
python turn_extractor.py snapshots_8_37.dat
python turn_extractor.py snapshots_3_211.dat
python turn_extractor.py snapshots_0_195.dat
python turn_extractor.py snapshots_8_143.dat
python turn_extractor.py snapshots_9_88.dat
python turn_extractor.py snapshots_0_16.dat
python turn_extractor.py snapshots_9_128.dat
python turn_extractor.py snapshots_3_9.dat
python turn_extractor.py snapshots_2_35.dat
python turn_extractor.py snapshots_9_59.dat
python turn_extractor.py snapshots_0_138.dat
python turn_extractor.py snapshots_5_238.dat
python turn_extractor.py snapshots_8_228.dat
python turn_extractor.py snapshots_3_27.dat
python turn_extractor.py snapshots_9_154.dat
python turn_extractor.py snapshots_7_61.dat
python turn_extractor.py snapshots_2_98.dat
python turn_extractor.py snapshots_5_93.dat
python turn_extractor.py snapshots_2_206.dat
python turn_extractor.py snapshots_4_3.dat
python turn_extractor.py snapshots_9_243.dat
python turn_extractor.py snapshots_5_42.dat
python turn_extractor.py snapshots_9_25.dat
python turn_extractor.py snapshots_2_111.dat
python turn_extractor.py snapshots_2_49.dat
python turn_extractor.py snapshots_9_185.dat
python turn_extractor.py snapshots_6_208.dat
python turn_extractor.py snapshots_3_108.dat
python turn_extractor.py snapshots_3_84.dat
python turn_extractor.py snapshots_1_76.dat
python turn_extractor.py snapshots_8_39.dat
python turn_extractor.py snapshots_3_55.dat
python turn_extractor.py snapshots_7_13.dat
python turn_extractor.py snapshots_9_126.dat
python turn_extractor.py snapshots_9_86.dat
python turn_extractor.py snapshots_0_18.dat
python turn_extractor.py snapshots_8_3.dat
python turn_extractor.py snapshots_3_7.dat
python turn_extractor.py snapshots_9_231.dat
python turn_extractor.py snapshots_9_57.dat
python turn_extractor.py snapshots_5_30.dat
python turn_extractor.py snapshots_3_174.dat
python turn_extractor.py snapshots_5_236.dat
python turn_extractor.py snapshots_0_136.dat
python turn_extractor.py snapshots_6_274.dat
python turn_extractor.py snapshots_8_226.dat
python turn_extractor.py snapshots_8_94.dat
python turn_extractor.py snapshots_0_221.dat
python turn_extractor.py snapshots_3_29.dat
python turn_extractor.py snapshots_6_163.dat
python turn_extractor.py snapshots_3_263.dat
python turn_extractor.py snapshots_8_45.dat
python turn_extractor.py snapshots_4_22.dat
python turn_extractor.py snapshots_5_121.dat
python turn_extractor.py snapshots_8_131.dat
python turn_extractor.py snapshots_2_96.dat
python turn_extractor.py snapshots_2_47.dat
python turn_extractor.py snapshots_3_173.dat
python turn_extractor.py snapshots_6_273.dat
python turn_extractor.py snapshots_0_131.dat
python turn_extractor.py snapshots_8_221.dat
python turn_extractor.py snapshots_8_93.dat
python turn_extractor.py snapshots_6_164.dat
python turn_extractor.py snapshots_0_226.dat
python turn_extractor.py snapshots_5_126.dat
python turn_extractor.py snapshots_8_42.dat
python turn_extractor.py snapshots_3_264.dat
python turn_extractor.py snapshots_8_136.dat
python turn_extractor.py snapshots_0_63.dat
python turn_extractor.py snapshots_2_91.dat
python turn_extractor.py snapshots_2_40.dat
python turn_extractor.py snapshots_2_118.dat
python turn_extractor.py snapshots_3_83.dat
python turn_extractor.py snapshots_4_88.dat
python turn_extractor.py snapshots_4_59.dat
python turn_extractor.py snapshots_3_218.dat
python turn_extractor.py snapshots_3_52.dat
python turn_extractor.py snapshots_6_118.dat
python turn_extractor.py snapshots_9_121.dat
python turn_extractor.py snapshots_7_14.dat
python turn_extractor.py snapshots_9_81.dat
python turn_extractor.py snapshots_8_4.dat
python turn_extractor.py snapshots_7_173.dat
python turn_extractor.py snapshots_9_236.dat
python turn_extractor.py snapshots_9_50.dat
python turn_extractor.py snapshots_5_37.dat
python turn_extractor.py snapshots_2_51.dat
python turn_extractor.py snapshots_2_109.dat
python turn_extractor.py snapshots_7_79.dat
python turn_extractor.py snapshots_2_80.dat
python turn_extractor.py snapshots_0_72.dat
python turn_extractor.py snapshots_8_53.dat
python turn_extractor.py snapshots_6_175.dat
python turn_extractor.py snapshots_0_237.dat
python turn_extractor.py snapshots_8_127.dat
python turn_extractor.py snapshots_6_262.dat
python turn_extractor.py snapshots_0_120.dat
python turn_extractor.py snapshots_5_220.dat
python turn_extractor.py snapshots_3_162.dat
python turn_extractor.py snapshots_6_17.dat
python turn_extractor.py snapshots_8_230.dat
python turn_extractor.py snapshots_8_82.dat
python turn_extractor.py snapshots_9_227.dat
python turn_extractor.py snapshots_9_41.dat
python turn_extractor.py snapshots_5_26.dat
python turn_extractor.py snapshots_9_90.dat
python turn_extractor.py snapshots_0_6.dat
python turn_extractor.py snapshots_9_130.dat
python turn_extractor.py snapshots_7_162.dat
python turn_extractor.py snapshots_4_120.dat
python turn_extractor.py snapshots_6_109.dat
python turn_extractor.py snapshots_3_43.dat
python turn_extractor.py snapshots_4_48.dat
python turn_extractor.py snapshots_3_209.dat
python turn_extractor.py snapshots_1_60.dat
python turn_extractor.py snapshots_4_99.dat
python turn_extractor.py snapshots_3_92.dat
python turn_extractor.py snapshots_9_220.dat
python turn_extractor.py snapshots_2_172.dat
python turn_extractor.py snapshots_9_46.dat
python turn_extractor.py snapshots_5_21.dat
python turn_extractor.py snapshots_0_1.dat
python turn_extractor.py snapshots_9_97.dat
python turn_extractor.py snapshots_9_137.dat
python turn_extractor.py snapshots_7_165.dat
python turn_extractor.py snapshots_3_44.dat
python turn_extractor.py snapshots_8_28.dat
python turn_extractor.py snapshots_3_119.dat
python turn_extractor.py snapshots_6_219.dat
python turn_extractor.py snapshots_3_95.dat
python turn_extractor.py snapshots_2_56.dat
python turn_extractor.py snapshots_2_87.dat
python turn_extractor.py snapshots_0_75.dat
python turn_extractor.py snapshots_5_130.dat
python turn_extractor.py snapshots_8_54.dat
python turn_extractor.py snapshots_0_230.dat
python turn_extractor.py snapshots_6_172.dat
python turn_extractor.py snapshots_3_38.dat
python turn_extractor.py snapshots_8_120.dat
python turn_extractor.py snapshots_0_127.dat
python turn_extractor.py snapshots_6_265.dat
python turn_extractor.py snapshots_3_165.dat
python turn_extractor.py snapshots_6_10.dat
python turn_extractor.py snapshots_8_237.dat
python turn_extractor.py snapshots_8_85.dat
python turn_extractor.py snapshots_9_48.dat
python turn_extractor.py snapshots_2_24.dat
python turn_extractor.py snapshots_9_139.dat
python turn_extractor.py snapshots_9_99.dat
python turn_extractor.py snapshots_8_26.dat
python turn_extractor.py snapshots_5_142.dat
python turn_extractor.py snapshots_3_200.dat
python turn_extractor.py snapshots_6_100.dat
python turn_extractor.py snapshots_0_242.dat
python turn_extractor.py snapshots_8_152.dat
python turn_extractor.py snapshots_0_184.dat
python turn_extractor.py snapshots_6_217.dat
python turn_extractor.py snapshots_0_155.dat
python turn_extractor.py snapshots_8_183.dat
python turn_extractor.py snapshots_3_117.dat
python turn_extractor.py snapshots_0_293.dat
python turn_extractor.py snapshots_6_62.dat
python turn_extractor.py snapshots_4_90.dat
python turn_extractor.py snapshots_8_245.dat
python turn_extractor.py snapshots_5_193.dat
python turn_extractor.py snapshots_2_100.dat
python turn_extractor.py snapshots_2_58.dat
python turn_extractor.py snapshots_9_194.dat
python turn_extractor.py snapshots_5_53.dat
python turn_extractor.py snapshots_9_34.dat
python turn_extractor.py snapshots_7_5.dat
python turn_extractor.py snapshots_5_82.dat
python turn_extractor.py snapshots_9_145.dat
python turn_extractor.py snapshots_2_89.dat
python turn_extractor.py snapshots_3_36.dat
python turn_extractor.py snapshots_0_129.dat
python turn_extractor.py snapshots_1_15.dat
python turn_extractor.py snapshots_8_239.dat
python turn_extractor.py snapshots_9_193.dat
python turn_extractor.py snapshots_2_107.dat
python turn_extractor.py snapshots_7_2.dat
python turn_extractor.py snapshots_5_54.dat
python turn_extractor.py snapshots_9_33.dat
python turn_extractor.py snapshots_5_85.dat
python turn_extractor.py snapshots_7_77.dat
python turn_extractor.py snapshots_9_142.dat
python turn_extractor.py snapshots_0_239.dat
python turn_extractor.py snapshots_3_31.dat
python turn_extractor.py snapshots_8_129.dat
python turn_extractor.py snapshots_1_12.dat
python turn_extractor.py snapshots_6_19.dat
python turn_extractor.py snapshots_9_229.dat
python turn_extractor.py snapshots_5_28.dat
python turn_extractor.py snapshots_2_23.dat
python turn_extractor.py snapshots_0_8.dat
python turn_extractor.py snapshots_3_207.dat
python turn_extractor.py snapshots_5_145.dat
python turn_extractor.py snapshots_8_21.dat
python turn_extractor.py snapshots_0_245.dat
python turn_extractor.py snapshots_6_107.dat
python turn_extractor.py snapshots_8_155.dat
python turn_extractor.py snapshots_0_183.dat
python turn_extractor.py snapshots_0_152.dat
python turn_extractor.py snapshots_6_210.dat
python turn_extractor.py snapshots_3_110.dat
python turn_extractor.py snapshots_8_184.dat
python turn_extractor.py snapshots_6_65.dat
python turn_extractor.py snapshots_0_294.dat
python turn_extractor.py snapshots_5_194.dat
python turn_extractor.py snapshots_8_242.dat
python turn_extractor.py snapshots_4_97.dat
python turn_extractor.py snapshots_0_49.dat
python turn_extractor.py snapshots_7_42.dat
python turn_extractor.py snapshots_9_177.dat
python turn_extractor.py snapshots_2_132.dat
python turn_extractor.py snapshots_5_61.dat
python turn_extractor.py snapshots_0_98.dat
python turn_extractor.py snapshots_9_260.dat
python turn_extractor.py snapshots_3_159.dat
python turn_extractor.py snapshots_6_259.dat
python turn_extractor.py snapshots_6_288.dat
python turn_extractor.py snapshots_3_188.dat
python turn_extractor.py snapshots_8_68.dat
python turn_extractor.py snapshots_7_159.dat
python turn_extractor.py snapshots_0_35.dat
python turn_extractor.py snapshots_2_16.dat
python turn_extractor.py snapshots_6_50.dat
python turn_extractor.py snapshots_8_277.dat
python turn_extractor.py snapshots_0_167.dat
python turn_extractor.py snapshots_6_225.dat
python turn_extractor.py snapshots_3_125.dat
python turn_extractor.py snapshots_8_160.dat
python turn_extractor.py snapshots_5_4.dat
python turn_extractor.py snapshots_3_232.dat
python turn_extractor.py snapshots_8_14.dat
python turn_extractor.py snapshots_4_73.dat
python turn_extractor.py snapshots_0_270.dat
python turn_extractor.py snapshots_3_78.dat
python turn_extractor.py snapshots_6_81.dat
python turn_extractor.py snapshots_6_132.dat
python turn_extractor.py snapshots_7_39.dat
python turn_extractor.py snapshots_0_32.dat
python turn_extractor.py snapshots_2_11.dat
python turn_extractor.py snapshots_2_149.dat
python turn_extractor.py snapshots_6_57.dat
python turn_extractor.py snapshots_8_270.dat
python turn_extractor.py snapshots_6_222.dat
python turn_extractor.py snapshots_0_160.dat
python turn_extractor.py snapshots_3_122.dat
python turn_extractor.py snapshots_5_3.dat
python turn_extractor.py snapshots_8_167.dat
python turn_extractor.py snapshots_8_13.dat
python turn_extractor.py snapshots_4_74.dat
python turn_extractor.py snapshots_3_235.dat
python turn_extractor.py snapshots_6_86.dat
python turn_extractor.py snapshots_6_135.dat
python turn_extractor.py snapshots_0_277.dat
python turn_extractor.py snapshots_9_170.dat
python turn_extractor.py snapshots_7_45.dat
python turn_extractor.py snapshots_2_135.dat
python turn_extractor.py snapshots_5_66.dat
python turn_extractor.py snapshots_9_267.dat
python turn_extractor.py snapshots_1_20.dat
python turn_extractor.py snapshots_6_198.dat
python turn_extractor.py snapshots_2_9.dat
python turn_extractor.py snapshots_6_149.dat
python turn_extractor.py snapshots_3_249.dat
python turn_extractor.py snapshots_7_37.dat
python turn_extractor.py snapshots_9_102.dat
python turn_extractor.py snapshots_2_147.dat
python turn_extractor.py snapshots_5_14.dat
python turn_extractor.py snapshots_9_73.dat
python turn_extractor.py snapshots_9_215.dat
python turn_extractor.py snapshots_6_59.dat
python turn_extractor.py snapshots_8_169.dat
python turn_extractor.py snapshots_0_279.dat
python turn_extractor.py snapshots_6_88.dat
python turn_extractor.py snapshots_3_71.dat
python turn_extractor.py snapshots_0_40.dat
python turn_extractor.py snapshots_0_91.dat
python turn_extractor.py snapshots_5_68.dat
python turn_extractor.py snapshots_2_63.dat
python turn_extractor.py snapshots_9_269.dat
python turn_extractor.py snapshots_6_25.dat
python turn_extractor.py snapshots_6_196.dat
python turn_extractor.py snapshots_8_202.dat
python turn_extractor.py snapshots_0_112.dat
python turn_extractor.py snapshots_6_250.dat
python turn_extractor.py snapshots_3_150.dat
python turn_extractor.py snapshots_2_7.dat
python turn_extractor.py snapshots_8_115.dat
python turn_extractor.py snapshots_3_181.dat
python turn_extractor.py snapshots_9_3.dat
python turn_extractor.py snapshots_6_281.dat
python turn_extractor.py snapshots_3_247.dat
python turn_extractor.py snapshots_8_61.dat
python turn_extractor.py snapshots_5_105.dat
python turn_extractor.py snapshots_0_205.dat
python turn_extractor.py snapshots_6_147.dat
python turn_extractor.py snapshots_9_179.dat
python turn_extractor.py snapshots_0_47.dat
python turn_extractor.py snapshots_0_96.dat
python turn_extractor.py snapshots_2_64.dat
python turn_extractor.py snapshots_6_22.dat
python turn_extractor.py snapshots_6_191.dat
python turn_extractor.py snapshots_8_205.dat
python turn_extractor.py snapshots_6_257.dat
python turn_extractor.py snapshots_0_115.dat
python turn_extractor.py snapshots_5_215.dat
python turn_extractor.py snapshots_3_157.dat
python turn_extractor.py snapshots_9_4.dat
python turn_extractor.py snapshots_3_186.dat
python turn_extractor.py snapshots_8_112.dat
python turn_extractor.py snapshots_6_286.dat
python turn_extractor.py snapshots_5_102.dat
python turn_extractor.py snapshots_8_66.dat
python turn_extractor.py snapshots_3_240.dat
python turn_extractor.py snapshots_6_140.dat
python turn_extractor.py snapshots_0_202.dat
python turn_extractor.py snapshots_7_157.dat
python turn_extractor.py snapshots_9_105.dat
python turn_extractor.py snapshots_7_30.dat
python turn_extractor.py snapshots_2_140.dat
python turn_extractor.py snapshots_2_18.dat
python turn_extractor.py snapshots_5_13.dat
python turn_extractor.py snapshots_9_74.dat
python turn_extractor.py snapshots_9_212.dat
python turn_extractor.py snapshots_8_279.dat
python turn_extractor.py snapshots_0_169.dat
python turn_extractor.py snapshots_3_76.dat
python turn_extractor.py snapshots_6_272.dat
python turn_extractor.py snapshots_0_130.dat
python turn_extractor.py snapshots_3_172.dat
python turn_extractor.py snapshots_8_92.dat
python turn_extractor.py snapshots_8_220.dat
python turn_extractor.py snapshots_8_43.dat
python turn_extractor.py snapshots_5_127.dat
python turn_extractor.py snapshots_3_265.dat
python turn_extractor.py snapshots_6_165.dat
python turn_extractor.py snapshots_0_227.dat
python turn_extractor.py snapshots_8_137.dat
python turn_extractor.py snapshots_2_90.dat
python turn_extractor.py snapshots_0_62.dat
python turn_extractor.py snapshots_2_119.dat
python turn_extractor.py snapshots_2_41.dat
python turn_extractor.py snapshots_4_89.dat
python turn_extractor.py snapshots_3_82.dat
python turn_extractor.py snapshots_6_119.dat
python turn_extractor.py snapshots_3_53.dat
python turn_extractor.py snapshots_4_58.dat
python turn_extractor.py snapshots_3_219.dat
python turn_extractor.py snapshots_9_80.dat
python turn_extractor.py snapshots_9_120.dat
python turn_extractor.py snapshots_7_15.dat
python turn_extractor.py snapshots_8_5.dat
python turn_extractor.py snapshots_7_172.dat
python turn_extractor.py snapshots_9_237.dat
python turn_extractor.py snapshots_3_1.dat
python turn_extractor.py snapshots_2_165.dat
python turn_extractor.py snapshots_5_36.dat
python turn_extractor.py snapshots_9_51.dat
python turn_extractor.py snapshots_3_109.dat
python turn_extractor.py snapshots_6_209.dat
python turn_extractor.py snapshots_1_77.dat
python turn_extractor.py snapshots_3_85.dat
python turn_extractor.py snapshots_3_54.dat
python turn_extractor.py snapshots_8_38.dat
python turn_extractor.py snapshots_0_19.dat
python turn_extractor.py snapshots_9_87.dat
python turn_extractor.py snapshots_7_12.dat
python turn_extractor.py snapshots_9_127.dat
python turn_extractor.py snapshots_8_2.dat
python turn_extractor.py snapshots_9_230.dat
python turn_extractor.py snapshots_3_6.dat
python turn_extractor.py snapshots_5_31.dat
python turn_extractor.py snapshots_9_56.dat
python turn_extractor.py snapshots_0_137.dat
python turn_extractor.py snapshots_3_175.dat
python turn_extractor.py snapshots_5_237.dat
python turn_extractor.py snapshots_8_95.dat
python turn_extractor.py snapshots_8_227.dat
python turn_extractor.py snapshots_3_262.dat
python turn_extractor.py snapshots_5_120.dat
python turn_extractor.py snapshots_8_44.dat
python turn_extractor.py snapshots_0_220.dat
python turn_extractor.py snapshots_6_162.dat
python turn_extractor.py snapshots_3_28.dat
python turn_extractor.py snapshots_8_130.dat
python turn_extractor.py snapshots_2_97.dat
python turn_extractor.py snapshots_2_46.dat
python turn_extractor.py snapshots_6_207.dat
python turn_extractor.py snapshots_0_145.dat
python turn_extractor.py snapshots_8_193.dat
python turn_extractor.py snapshots_3_107.dat
python turn_extractor.py snapshots_0_283.dat
python turn_extractor.py snapshots_6_72.dat
python turn_extractor.py snapshots_4_80.dat
python turn_extractor.py snapshots_8_255.dat
python turn_extractor.py snapshots_1_79.dat
python turn_extractor.py snapshots_8_36.dat
python turn_extractor.py snapshots_4_51.dat
python turn_extractor.py snapshots_8_284.dat
python turn_extractor.py snapshots_5_152.dat
python turn_extractor.py snapshots_3_210.dat
python turn_extractor.py snapshots_6_110.dat
python turn_extractor.py snapshots_0_252.dat
python turn_extractor.py snapshots_8_142.dat
python turn_extractor.py snapshots_0_194.dat
python turn_extractor.py snapshots_9_129.dat
python turn_extractor.py snapshots_0_17.dat
python turn_extractor.py snapshots_9_89.dat
python turn_extractor.py snapshots_3_8.dat
python turn_extractor.py snapshots_9_58.dat
python turn_extractor.py snapshots_2_34.dat
python turn_extractor.py snapshots_0_139.dat
python turn_extractor.py snapshots_8_229.dat
python turn_extractor.py snapshots_3_26.dat
python turn_extractor.py snapshots_5_92.dat
python turn_extractor.py snapshots_9_155.dat
python turn_extractor.py snapshots_2_99.dat
python turn_extractor.py snapshots_7_60.dat
python turn_extractor.py snapshots_4_2.dat
python turn_extractor.py snapshots_2_207.dat
python turn_extractor.py snapshots_9_242.dat
python turn_extractor.py snapshots_2_48.dat
python turn_extractor.py snapshots_2_110.dat
python turn_extractor.py snapshots_9_184.dat
python turn_extractor.py snapshots_9_24.dat
python turn_extractor.py snapshots_5_43.dat
python turn_extractor.py snapshots_0_229.dat
python turn_extractor.py snapshots_3_21.dat
python turn_extractor.py snapshots_5_129.dat
python turn_extractor.py snapshots_8_139.dat
python turn_extractor.py snapshots_5_95.dat
python turn_extractor.py snapshots_9_152.dat
python turn_extractor.py snapshots_7_100.dat
python turn_extractor.py snapshots_4_5.dat
python turn_extractor.py snapshots_9_245.dat
python turn_extractor.py snapshots_9_183.dat
python turn_extractor.py snapshots_2_117.dat
python turn_extractor.py snapshots_9_23.dat
python turn_extractor.py snapshots_5_44.dat
python turn_extractor.py snapshots_0_142.dat
python turn_extractor.py snapshots_6_200.dat
python turn_extractor.py snapshots_3_100.dat
python turn_extractor.py snapshots_8_194.dat
python turn_extractor.py snapshots_6_75.dat
python turn_extractor.py snapshots_0_284.dat
python turn_extractor.py snapshots_8_252.dat
python turn_extractor.py snapshots_4_87.dat
python turn_extractor.py snapshots_3_217.dat
python turn_extractor.py snapshots_5_155.dat
python turn_extractor.py snapshots_8_31.dat
python turn_extractor.py snapshots_8_283.dat
python turn_extractor.py snapshots_4_56.dat
python turn_extractor.py snapshots_0_255.dat
python turn_extractor.py snapshots_6_117.dat
python turn_extractor.py snapshots_8_145.dat
python turn_extractor.py snapshots_0_193.dat
python turn_extractor.py snapshots_0_10.dat
python turn_extractor.py snapshots_9_239.dat
python turn_extractor.py snapshots_5_38.dat
python turn_extractor.py snapshots_2_33.dat
python turn_extractor.py snapshots_3_198.dat
python turn_extractor.py snapshots_3_14.dat
python turn_extractor.py snapshots_1_9.dat
python turn_extractor.py snapshots_8_78.dat
python turn_extractor.py snapshots_1_37.dat
python turn_extractor.py snapshots_3_149.dat
python turn_extractor.py snapshots_6_249.dat
python turn_extractor.py snapshots_2_122.dat
python turn_extractor.py snapshots_7_83.dat
python turn_extractor.py snapshots_5_71.dat
python turn_extractor.py snapshots_9_16.dat
python turn_extractor.py snapshots_0_88.dat
python turn_extractor.py snapshots_9_270.dat
python turn_extractor.py snapshots_7_135.dat
python turn_extractor.py snapshots_0_59.dat
python turn_extractor.py snapshots_9_167.dat
python turn_extractor.py snapshots_8_170.dat
python turn_extractor.py snapshots_3_222.dat
python turn_extractor.py snapshots_4_63.dat
python turn_extractor.py snapshots_3_68.dat
python turn_extractor.py snapshots_6_122.dat
python turn_extractor.py snapshots_6_91.dat
python turn_extractor.py snapshots_6_40.dat
python turn_extractor.py snapshots_8_267.dat
python turn_extractor.py snapshots_6_3.dat
python turn_extractor.py snapshots_0_177.dat
python turn_extractor.py snapshots_6_235.dat
python turn_extractor.py snapshots_3_135.dat
python turn_extractor.py snapshots_0_25.dat
python turn_extractor.py snapshots_8_177.dat
python turn_extractor.py snapshots_4_64.dat
python turn_extractor.py snapshots_3_225.dat
python turn_extractor.py snapshots_6_125.dat
python turn_extractor.py snapshots_6_96.dat
python turn_extractor.py snapshots_0_267.dat
python turn_extractor.py snapshots_6_47.dat
python turn_extractor.py snapshots_6_4.dat
python turn_extractor.py snapshots_8_260.dat
python turn_extractor.py snapshots_6_232.dat
python turn_extractor.py snapshots_0_170.dat
python turn_extractor.py snapshots_3_132.dat
python turn_extractor.py snapshots_2_159.dat
python turn_extractor.py snapshots_2_188.dat
python turn_extractor.py snapshots_7_29.dat
python turn_extractor.py snapshots_0_22.dat
python turn_extractor.py snapshots_3_13.dat
python turn_extractor.py snapshots_6_159.dat
python turn_extractor.py snapshots_4_18.dat
python turn_extractor.py snapshots_3_259.dat
python turn_extractor.py snapshots_6_188.dat
python turn_extractor.py snapshots_7_84.dat
python turn_extractor.py snapshots_2_125.dat
python turn_extractor.py snapshots_5_76.dat
python turn_extractor.py snapshots_9_11.dat
python turn_extractor.py snapshots_7_132.dat
python turn_extractor.py snapshots_9_160.dat
python turn_extractor.py snapshots_7_55.dat
python turn_extractor.py snapshots_8_179.dat
python turn_extractor.py snapshots_0_269.dat
python turn_extractor.py snapshots_6_98.dat
python turn_extractor.py snapshots_3_61.dat
python turn_extractor.py snapshots_1_42.dat
python turn_extractor.py snapshots_6_49.dat
python turn_extractor.py snapshots_2_157.dat
python turn_extractor.py snapshots_9_63.dat
python turn_extractor.py snapshots_9_205.dat
python turn_extractor.py snapshots_4_102.dat
python turn_extractor.py snapshots_2_186.dat
python turn_extractor.py snapshots_7_27.dat
python turn_extractor.py snapshots_9_112.dat
python turn_extractor.py snapshots_8_105.dat
python turn_extractor.py snapshots_3_191.dat
python turn_extractor.py snapshots_3_257.dat
python turn_extractor.py snapshots_8_71.dat
python turn_extractor.py snapshots_4_16.dat
python turn_extractor.py snapshots_5_115.dat
python turn_extractor.py snapshots_0_215.dat
python turn_extractor.py snapshots_6_157.dat
python turn_extractor.py snapshots_6_186.dat
python turn_extractor.py snapshots_6_35.dat
python turn_extractor.py snapshots_8_212.dat
python turn_extractor.py snapshots_0_102.dat
python turn_extractor.py snapshots_6_240.dat
python turn_extractor.py snapshots_3_140.dat
python turn_extractor.py snapshots_5_202.dat
python turn_extractor.py snapshots_0_81.dat
python turn_extractor.py snapshots_5_78.dat
python turn_extractor.py snapshots_2_73.dat
python turn_extractor.py snapshots_0_50.dat
python turn_extractor.py snapshots_3_196.dat
python turn_extractor.py snapshots_8_102.dat
python turn_extractor.py snapshots_5_112.dat
python turn_extractor.py snapshots_8_76.dat
python turn_extractor.py snapshots_4_11.dat
python turn_extractor.py snapshots_3_250.dat
python turn_extractor.py snapshots_1_7.dat
python turn_extractor.py snapshots_6_150.dat
python turn_extractor.py snapshots_0_212.dat
python turn_extractor.py snapshots_6_181.dat
python turn_extractor.py snapshots_6_32.dat
python turn_extractor.py snapshots_1_39.dat
python turn_extractor.py snapshots_8_215.dat
python turn_extractor.py snapshots_6_247.dat
python turn_extractor.py snapshots_0_105.dat
python turn_extractor.py snapshots_5_205.dat
python turn_extractor.py snapshots_3_147.dat
python turn_extractor.py snapshots_9_18.dat
python turn_extractor.py snapshots_0_86.dat
python turn_extractor.py snapshots_2_74.dat
python turn_extractor.py snapshots_9_169.dat
python turn_extractor.py snapshots_0_57.dat
python turn_extractor.py snapshots_3_66.dat
python turn_extractor.py snapshots_8_269.dat
python turn_extractor.py snapshots_1_45.dat
python turn_extractor.py snapshots_0_179.dat
python turn_extractor.py snapshots_2_150.dat
python turn_extractor.py snapshots_9_64.dat
python turn_extractor.py snapshots_9_202.dat
python turn_extractor.py snapshots_4_105.dat
python turn_extractor.py snapshots_9_115.dat
python turn_extractor.py snapshots_7_20.dat
python turn_extractor.py snapshots_2_181.dat
python turn_extractor.py snapshots_0_46.dat
python turn_extractor.py snapshots_9_178.dat
python turn_extractor.py snapshots_2_65.dat
python turn_extractor.py snapshots_0_97.dat
python turn_extractor.py snapshots_8_204.dat
python turn_extractor.py snapshots_6_190.dat
python turn_extractor.py snapshots_6_23.dat
python turn_extractor.py snapshots_5_214.dat
python turn_extractor.py snapshots_2_1.dat
python turn_extractor.py snapshots_3_156.dat
python turn_extractor.py snapshots_6_256.dat
python turn_extractor.py snapshots_0_114.dat
python turn_extractor.py snapshots_6_287.dat
python turn_extractor.py snapshots_3_187.dat
python turn_extractor.py snapshots_9_5.dat
python turn_extractor.py snapshots_8_113.dat
python turn_extractor.py snapshots_6_141.dat
python turn_extractor.py snapshots_0_203.dat
python turn_extractor.py snapshots_8_67.dat
python turn_extractor.py snapshots_5_103.dat
python turn_extractor.py snapshots_7_156.dat
python turn_extractor.py snapshots_9_104.dat
python turn_extractor.py snapshots_2_190.dat
python turn_extractor.py snapshots_7_31.dat
python turn_extractor.py snapshots_9_75.dat
python turn_extractor.py snapshots_5_12.dat
python turn_extractor.py snapshots_2_19.dat
python turn_extractor.py snapshots_2_141.dat
python turn_extractor.py snapshots_9_213.dat
python turn_extractor.py snapshots_8_278.dat
python turn_extractor.py snapshots_0_168.dat
python turn_extractor.py snapshots_3_77.dat
python turn_extractor.py snapshots_7_36.dat
python turn_extractor.py snapshots_9_103.dat
python turn_extractor.py snapshots_9_72.dat
python turn_extractor.py snapshots_5_15.dat
python turn_extractor.py snapshots_2_146.dat
python turn_extractor.py snapshots_9_214.dat
python turn_extractor.py snapshots_6_58.dat
python turn_extractor.py snapshots_1_53.dat
python turn_extractor.py snapshots_8_168.dat
python turn_extractor.py snapshots_0_278.dat
python turn_extractor.py snapshots_3_70.dat
python turn_extractor.py snapshots_6_89.dat
python turn_extractor.py snapshots_0_41.dat
python turn_extractor.py snapshots_2_62.dat
python turn_extractor.py snapshots_5_69.dat
python turn_extractor.py snapshots_0_90.dat
python turn_extractor.py snapshots_9_268.dat
python turn_extractor.py snapshots_8_203.dat
python turn_extractor.py snapshots_6_197.dat
python turn_extractor.py snapshots_6_24.dat
python turn_extractor.py snapshots_2_6.dat
python turn_extractor.py snapshots_3_151.dat
python turn_extractor.py snapshots_0_113.dat
python turn_extractor.py snapshots_6_251.dat
python turn_extractor.py snapshots_6_280.dat
python turn_extractor.py snapshots_8_114.dat
python turn_extractor.py snapshots_9_2.dat
python turn_extractor.py snapshots_3_180.dat
python turn_extractor.py snapshots_0_204.dat
python turn_extractor.py snapshots_6_146.dat
python turn_extractor.py snapshots_3_246.dat
python turn_extractor.py snapshots_5_104.dat
python turn_extractor.py snapshots_8_60.dat
python turn_extractor.py snapshots_0_33.dat
python turn_extractor.py snapshots_7_38.dat
python turn_extractor.py snapshots_2_148.dat
python turn_extractor.py snapshots_2_10.dat
python turn_extractor.py snapshots_8_271.dat
python turn_extractor.py snapshots_6_56.dat
python turn_extractor.py snapshots_3_123.dat
python turn_extractor.py snapshots_6_223.dat
python turn_extractor.py snapshots_0_161.dat
python turn_extractor.py snapshots_5_2.dat
python turn_extractor.py snapshots_8_166.dat
python turn_extractor.py snapshots_6_134.dat
python turn_extractor.py snapshots_6_87.dat
python turn_extractor.py snapshots_0_276.dat
python turn_extractor.py snapshots_4_75.dat
python turn_extractor.py snapshots_8_12.dat
python turn_extractor.py snapshots_3_234.dat
python turn_extractor.py snapshots_9_171.dat
python turn_extractor.py snapshots_7_44.dat
python turn_extractor.py snapshots_5_67.dat
python turn_extractor.py snapshots_2_134.dat
python turn_extractor.py snapshots_9_266.dat
python turn_extractor.py snapshots_6_199.dat
python turn_extractor.py snapshots_2_8.dat
python turn_extractor.py snapshots_3_248.dat
python turn_extractor.py snapshots_6_148.dat
python turn_extractor.py snapshots_7_43.dat
python turn_extractor.py snapshots_9_176.dat
python turn_extractor.py snapshots_0_48.dat
python turn_extractor.py snapshots_0_99.dat
python turn_extractor.py snapshots_5_60.dat
python turn_extractor.py snapshots_2_133.dat
python turn_extractor.py snapshots_9_261.dat
python turn_extractor.py snapshots_6_258.dat
python turn_extractor.py snapshots_3_158.dat
python turn_extractor.py snapshots_3_189.dat
python turn_extractor.py snapshots_6_289.dat
python turn_extractor.py snapshots_8_69.dat
python turn_extractor.py snapshots_7_158.dat
python turn_extractor.py snapshots_0_34.dat
python turn_extractor.py snapshots_2_17.dat
python turn_extractor.py snapshots_8_276.dat
python turn_extractor.py snapshots_6_51.dat
python turn_extractor.py snapshots_3_124.dat
python turn_extractor.py snapshots_0_166.dat
python turn_extractor.py snapshots_6_224.dat
python turn_extractor.py snapshots_8_161.dat
python turn_extractor.py snapshots_5_5.dat
python turn_extractor.py snapshots_0_271.dat
python turn_extractor.py snapshots_6_133.dat
python turn_extractor.py snapshots_6_80.dat
python turn_extractor.py snapshots_3_79.dat
python turn_extractor.py snapshots_3_233.dat
python turn_extractor.py snapshots_4_72.dat
python turn_extractor.py snapshots_8_15.dat
python turn_extractor.py snapshots_9_32.dat
python turn_extractor.py snapshots_5_55.dat
python turn_extractor.py snapshots_7_3.dat
python turn_extractor.py snapshots_9_192.dat
python turn_extractor.py snapshots_2_106.dat
python turn_extractor.py snapshots_7_76.dat
python turn_extractor.py snapshots_9_143.dat
python turn_extractor.py snapshots_5_84.dat
python turn_extractor.py snapshots_0_238.dat
python turn_extractor.py snapshots_3_30.dat
python turn_extractor.py snapshots_8_128.dat
python turn_extractor.py snapshots_6_18.dat
python turn_extractor.py snapshots_1_13.dat
python turn_extractor.py snapshots_9_228.dat
python turn_extractor.py snapshots_2_22.dat
python turn_extractor.py snapshots_5_29.dat
python turn_extractor.py snapshots_0_9.dat
python turn_extractor.py snapshots_0_244.dat
python turn_extractor.py snapshots_6_106.dat
python turn_extractor.py snapshots_3_206.dat
python turn_extractor.py snapshots_8_20.dat
python turn_extractor.py snapshots_8_292.dat
python turn_extractor.py snapshots_5_144.dat
python turn_extractor.py snapshots_0_182.dat
python turn_extractor.py snapshots_8_154.dat
python turn_extractor.py snapshots_3_111.dat
python turn_extractor.py snapshots_8_185.dat
python turn_extractor.py snapshots_0_153.dat
python turn_extractor.py snapshots_6_211.dat
python turn_extractor.py snapshots_8_243.dat
python turn_extractor.py snapshots_4_96.dat
python turn_extractor.py snapshots_5_195.dat
python turn_extractor.py snapshots_6_64.dat
python turn_extractor.py snapshots_0_295.dat
python turn_extractor.py snapshots_2_25.dat
python turn_extractor.py snapshots_9_49.dat
python turn_extractor.py snapshots_9_98.dat
python turn_extractor.py snapshots_9_138.dat
python turn_extractor.py snapshots_6_101.dat
python turn_extractor.py snapshots_0_243.dat
python turn_extractor.py snapshots_5_143.dat
python turn_extractor.py snapshots_8_27.dat
python turn_extractor.py snapshots_3_201.dat
python turn_extractor.py snapshots_0_185.dat
python turn_extractor.py snapshots_8_153.dat
python turn_extractor.py snapshots_8_182.dat
python turn_extractor.py snapshots_3_116.dat
python turn_extractor.py snapshots_6_216.dat
python turn_extractor.py snapshots_0_154.dat
python turn_extractor.py snapshots_5_192.dat
python turn_extractor.py snapshots_4_91.dat
python turn_extractor.py snapshots_8_244.dat
python turn_extractor.py snapshots_0_292.dat
python turn_extractor.py snapshots_6_63.dat
python turn_extractor.py snapshots_7_4.dat
python turn_extractor.py snapshots_9_35.dat
python turn_extractor.py snapshots_5_52.dat
python turn_extractor.py snapshots_2_59.dat
python turn_extractor.py snapshots_2_101.dat
python turn_extractor.py snapshots_9_195.dat
python turn_extractor.py snapshots_9_144.dat
python turn_extractor.py snapshots_2_88.dat
python turn_extractor.py snapshots_5_83.dat
python turn_extractor.py snapshots_3_37.dat
python turn_extractor.py snapshots_0_128.dat
python turn_extractor.py snapshots_8_238.dat
python turn_extractor.py snapshots_1_14.dat
python turn_extractor.py snapshots_9_221.dat
python turn_extractor.py snapshots_5_20.dat
python turn_extractor.py snapshots_9_47.dat
python turn_extractor.py snapshots_9_136.dat
python turn_extractor.py snapshots_9_96.dat
python turn_extractor.py snapshots_7_164.dat
python turn_extractor.py snapshots_8_29.dat
python turn_extractor.py snapshots_3_45.dat
python turn_extractor.py snapshots_6_218.dat
python turn_extractor.py snapshots_3_118.dat
python turn_extractor.py snapshots_3_94.dat
python turn_extractor.py snapshots_2_57.dat
python turn_extractor.py snapshots_0_74.dat
python turn_extractor.py snapshots_2_86.dat
python turn_extractor.py snapshots_0_231.dat
python turn_extractor.py snapshots_3_39.dat
python turn_extractor.py snapshots_6_173.dat
python turn_extractor.py snapshots_8_55.dat
python turn_extractor.py snapshots_5_131.dat
python turn_extractor.py snapshots_8_121.dat
python turn_extractor.py snapshots_3_164.dat
python turn_extractor.py snapshots_0_126.dat
python turn_extractor.py snapshots_6_264.dat
python turn_extractor.py snapshots_8_84.dat
python turn_extractor.py snapshots_8_236.dat
python turn_extractor.py snapshots_6_11.dat
python turn_extractor.py snapshots_2_108.dat
python turn_extractor.py snapshots_2_50.dat
python turn_extractor.py snapshots_0_73.dat
python turn_extractor.py snapshots_2_81.dat
python turn_extractor.py snapshots_7_78.dat
python turn_extractor.py snapshots_6_174.dat
python turn_extractor.py snapshots_0_236.dat
python turn_extractor.py snapshots_8_52.dat
python turn_extractor.py snapshots_8_126.dat
python turn_extractor.py snapshots_5_221.dat
python turn_extractor.py snapshots_3_163.dat
python turn_extractor.py snapshots_6_263.dat
python turn_extractor.py snapshots_0_121.dat
python turn_extractor.py snapshots_8_83.dat
python turn_extractor.py snapshots_8_231.dat
python turn_extractor.py snapshots_6_16.dat
python turn_extractor.py snapshots_9_226.dat
python turn_extractor.py snapshots_5_27.dat
python turn_extractor.py snapshots_9_40.dat
python turn_extractor.py snapshots_9_131.dat
python turn_extractor.py snapshots_9_91.dat
python turn_extractor.py snapshots_0_7.dat
python turn_extractor.py snapshots_4_121.dat
python turn_extractor.py snapshots_4_49.dat
python turn_extractor.py snapshots_3_208.dat
python turn_extractor.py snapshots_3_42.dat
python turn_extractor.py snapshots_6_108.dat
python turn_extractor.py snapshots_3_93.dat
python turn_extractor.py snapshots_4_98.dat
